name: zlib-CMake
on: [push]
jobs:
  ci-cmake:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu-GCC
            os: ubuntu-22.04
            compiler: gcc
            cflags: -g -O1

          - name: Ubuntu-GCC-O3
            os: ubuntu-22.04
            compiler: gcc
            cflags: -g -O3

          - name: Ubuntu-Clang
            os: ubuntu-22.04
            compiler: clang

          - name: Ubuntu-Clang-Debug
            os: ubuntu-22.04
            compiler: clang
            build-config: Debug

          - name: Windows-MSVC-Win32
            os: windows-2022
            compiler: cl
            arch: x86
            cmake-args: -G Ninja
            sed: C:\msys64\usr\bin\sed.exe -i

          - name: Windows-MSVC-Win64
            os: windows-2022
            compiler: cl
            cmake-args: -G Ninja
            sed: C:\msys64\usr\bin\sed.exe -i

          - name: Windows-GCC
            os: windows-2022
            compiler: gcc
            cmake-args: -G Ninja
            cflags: -g -O1
            sed: C:\msys64\usr\bin\sed.exe -i

          - name: macOS-Clang
            os: macos-12
            compiler: clang
            cflags: -g -O1
            sed: sed -i '' -e

          - name: macOS-GCC
            os: macos-12
            compiler: gcc-11
            sed: sed -i '' -e

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: madler/zlib

    - name: Install packages (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install --no-progress ninja ${{ matrix.packages }}

    - name: Setup MSVC-CMD (Windows)
      uses: ilammy/msvc-dev-cmd@v1
      if: runner.os == 'Windows'
      with:
        arch: ${{ matrix.arch || 'x64' }}
        vsversion: '2022'

    - name: Generate project files
      run: |
        cmake -S ${{ matrix.src-dir || '.' }} -B ${{ matrix.build-dir || '.' }} ${{ matrix.cmake-args }} -D CMAKE_BUILD_TYPE=${{ matrix.build-config || 'RelWithDebInfo' }}
        ${{ matrix.sed || 'sed -i' }} '/CMAKE_C_FLAGS/s/O[023sd]/O1/' ${{ matrix.build-dir || '.' }}/CMakeCache.txt
        ninja --version || echo NO NINJA
      env:
        CC: ${{ matrix.compiler }}
        CFLAGS: ${{ matrix.cflags }}

    - name: Compile source code
      run: cmake --build ${{ matrix.build-dir || '.' }} --config ${{ matrix.build-config || 'RelWithDebInfo' }} --verbose

    - name: Save debug info
      if: runner.os == 'macOS'
      run: |
        dsymutil libz.dylib

    - name: Run test cases
      run: ctest -C RelWithDebInfo --output-on-failure --max-width 120
      working-directory: ${{ matrix.build-dir || '.' }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.name }}
        path: |
          **/zlib.dll
          **/zlib.pdb
          **/libz*.dylib
          **/libz.dylib.dSYM
          **/libz.so
          **/libzlib.dll
        retention-days: 2

  combine:
    name: Combine artifacts
    needs: ci-cmake
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with: 
        path: builds

    - name: Show downloaded files
      run: find builds -type f -ls

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: zlib-builds
        path: builds/**
        retention-days: 7

